---
title: python调用本地wps添加水印
date: 2022-08-30
categories:
  -  Python
tags:
  -  watermark
sticky: 1
prev: 252229.md
next:
---



<!-- more -->

## doc类型文件添加水印

java POI等只能给docx类型的文件添加水印，其他需要收费


## 安装依赖

```bash
pip install pypywin32
```


```python
# coding:utf8
import win32com
from win32com.client import Dispatch, constants
def getWordAddWatermark():
    wordApp = win32com.client.DispatchEx("KWPS.Application")  # 打开word进程
    wordApp.Visible = True
    wordApp.DisplayAlerts = False
    doc = wordApp.Documents.Open("C:\\data\\space\\watermark\\cc.doc")  # 打开文件

    actDoc = wordApp.ActiveDocument
    actDoc.Sections(1).Range.Select()
    wordApp.ActiveWindow.ActivePane.View.SeekView = 9
    # selectObj = wordApp.Selection

    wordApp.Selection.HeaderFooter.Shapes.AddTextEffect(0, "我是一个水印", "等线", 1, False, False, 0, 0).Select()
    # shpObj = vart.Select()
    wordApp.Selection.ShapeRange.Name = 'WaterMark' 

    wordApp.Selection.ShapeRange.TextEffect.NormalizedHeight = False
    wordApp.Selection.ShapeRange.Line.Visible = False
    wordApp.Selection.ShapeRange.Fill.Visible = True
    wordApp.Selection.ShapeRange.Fill.Solid
    wordApp.Selection.ShapeRange.Fill.ForeColor = 0
    wordApp.Selection.ShapeRange.Fill.Transparency = 0.5
    # 设置颜色
    wordApp.Selection.ShapeRange.Fill.ForeColor.RGB = 12632256
    wordApp.Selection.ShapeRange.Fill.ForeColor.TintAndShade = 0
    wordApp.Selection.ShapeRange.Rotation = 315
    wordApp.Selection.ShapeRange.LockAspectRatio = True
    wordApp.Selection.ShapeRange.Height = 120
    wordApp.Selection.ShapeRange.Width = 460
    wordApp.Selection.ShapeRange.WrapFormat.AllowOverlap = True
    # wordApp.Selection.ShapeRange.WrapFormat.Side = wdWrapNone
    wordApp.Selection.ShapeRange.WrapFormat.Type = 3
    wordApp.Selection.ShapeRange.WrapFormat.Side = 3
    wordApp.Selection.ShapeRange.RelativeVerticalPosition = 0
    wordApp.Selection.ShapeRange.Left = -999995
    wordApp.Selection.ShapeRange.Top = -999995

    # 这里出问题了，提示没有select这个方法
    # wordApp.Selection.HeaderFooter.Shapes("0").Select
    # wordApp.Selection.ShapeRange.Duplicate.select
    # wordApp.Selection.ShapeRange.IncrementLeft(-426.8)
    # wordApp.Selection.ShapeRange.IncrementTop(403.85)
    # 关闭页眉页脚
    wordApp.ActiveWindow.ActivePane.View.SeekView = 0
    doc.Save()
    # actDoc.Close()
    wordApp.Quit()

if __name__ == '__main__':
    getWordAddWatermark()

```